// <auto-generated />
using BooksAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksAPI.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20241028192802_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksAPI.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("ISBNNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookCategoryId = 1,
                            BookName = "To Kill a Mockingbird",
                            Edition = 1,
                            ISBNNumber = "978-0-06-093546-5",
                            ListPrice = 14.99m,
                            Pages = 281m,
                            StandardCost = 8.99m,
                            Writer = "Harper Lee"
                        },
                        new
                        {
                            BookId = 2,
                            BookCategoryId = 7,
                            BookName = "1984",
                            Edition = 1,
                            ISBNNumber = "978-0-451-52493-5",
                            ListPrice = 16.99m,
                            Pages = 328m,
                            StandardCost = 9.99m,
                            Writer = "George Orwell"
                        },
                        new
                        {
                            BookId = 3,
                            BookCategoryId = 1,
                            BookName = "The Great Gatsby",
                            Edition = 1,
                            ISBNNumber = "978-0-7432-7356-5",
                            ListPrice = 17.99m,
                            Pages = 180m,
                            StandardCost = 10.99m,
                            Writer = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            BookId = 4,
                            BookCategoryId = 7,
                            BookName = "The Hunger Games",
                            Edition = 1,
                            ISBNNumber = "978-0-439-02352-8",
                            ListPrice = 19.99m,
                            Pages = 374m,
                            StandardCost = 11.99m,
                            Writer = "Suzanne Collins"
                        },
                        new
                        {
                            BookId = 5,
                            BookCategoryId = 5,
                            BookName = "The Diary of a Young Girl",
                            Edition = 1,
                            ISBNNumber = "978-0-553-57712-8",
                            ListPrice = 12.99m,
                            Pages = 283m,
                            StandardCost = 7.99m,
                            Writer = "Anne Frank"
                        },
                        new
                        {
                            BookId = 6,
                            BookCategoryId = 4,
                            BookName = "Pride and Prejudice",
                            Edition = 1,
                            ISBNNumber = "978-0-141-43951-8",
                            ListPrice = 14.99m,
                            Pages = 279m,
                            StandardCost = 8.99m,
                            Writer = "Jane Austen"
                        },
                        new
                        {
                            BookId = 7,
                            BookCategoryId = 1,
                            BookName = "The Kite Runner",
                            Edition = 1,
                            ISBNNumber = "978-1-59448-000-3",
                            ListPrice = 19.99m,
                            Pages = 371m,
                            StandardCost = 11.99m,
                            Writer = "Khaled Hosseini"
                        },
                        new
                        {
                            BookId = 8,
                            BookCategoryId = 1,
                            BookName = "The Book Thief",
                            Edition = 1,
                            ISBNNumber = "978-0-375-84220-7",
                            ListPrice = 17.99m,
                            Pages = 572m,
                            StandardCost = 10.99m,
                            Writer = "Markus Zusak"
                        },
                        new
                        {
                            BookId = 9,
                            BookCategoryId = 3,
                            BookName = "The Girl on the Train",
                            Edition = 1,
                            ISBNNumber = "978-1-59463-369-6",
                            ListPrice = 16.99m,
                            Pages = 323m,
                            StandardCost = 9.99m,
                            Writer = "Paula Hawkins"
                        },
                        new
                        {
                            BookId = 10,
                            BookCategoryId = 9,
                            BookName = "The Life-Changing Magic of Tidying Up",
                            Edition = 1,
                            ISBNNumber = "978-1-60774-818-4",
                            ListPrice = 21.99m,
                            Pages = 224m,
                            StandardCost = 12.99m,
                            Writer = "Marie Kondo"
                        },
                        new
                        {
                            BookId = 11,
                            BookCategoryId = 2,
                            BookName = "Sapiens: A Brief History of Humankind",
                            Edition = 1,
                            ISBNNumber = "978-0-062-31622-7",
                            ListPrice = 24.99m,
                            Pages = 443m,
                            StandardCost = 14.99m,
                            Writer = "Yuval Noah Harari"
                        },
                        new
                        {
                            BookId = 12,
                            BookCategoryId = 8,
                            BookName = "The Lord of the Rings",
                            Edition = 2,
                            ISBNNumber = "978-0-618-64015-7",
                            ListPrice = 27.99m,
                            Pages = 1178m,
                            StandardCost = 15.99m,
                            Writer = "J.R.R. Tolkien"
                        },
                        new
                        {
                            BookId = 13,
                            BookCategoryId = 17,
                            BookName = "In Cold Blood",
                            Edition = 1,
                            ISBNNumber = "978-0-679-74558-7",
                            ListPrice = 19.99m,
                            Pages = 343m,
                            StandardCost = 11.99m,
                            Writer = "Truman Capote"
                        },
                        new
                        {
                            BookId = 14,
                            BookCategoryId = 18,
                            BookName = "The Shining",
                            Edition = 1,
                            ISBNNumber = "978-0-307-74365-7",
                            ListPrice = 21.99m,
                            Pages = 447m,
                            StandardCost = 12.99m,
                            Writer = "Stephen King"
                        },
                        new
                        {
                            BookId = 15,
                            BookCategoryId = 16,
                            BookName = "The Republic",
                            Edition = 2,
                            ISBNNumber = "978-0-465-06934-7",
                            ListPrice = 16.99m,
                            Pages = 416m,
                            StandardCost = 9.99m,
                            Writer = "Plato"
                        },
                        new
                        {
                            BookId = 16,
                            BookCategoryId = 21,
                            BookName = "Thinking, Fast and Slow",
                            Edition = 1,
                            ISBNNumber = "978-0-374-53355-7",
                            ListPrice = 22.99m,
                            Pages = 499m,
                            StandardCost = 13.99m,
                            Writer = "Daniel Kahneman"
                        },
                        new
                        {
                            BookId = 17,
                            BookCategoryId = 16,
                            BookName = "The Art of War",
                            Edition = 1,
                            ISBNNumber = "978-0-486-42556-3",
                            ListPrice = 9.99m,
                            Pages = 273m,
                            StandardCost = 5.99m,
                            Writer = "Sun Tzu"
                        },
                        new
                        {
                            BookId = 18,
                            BookCategoryId = 25,
                            BookName = "A Brief History of Time",
                            Edition = 1,
                            ISBNNumber = "978-0-553-17698-7",
                            ListPrice = 18.99m,
                            Pages = 256m,
                            StandardCost = 10.99m,
                            Writer = "Stephen Hawking"
                        },
                        new
                        {
                            BookId = 19,
                            BookCategoryId = 13,
                            BookName = "Good to Great",
                            Edition = 1,
                            ISBNNumber = "978-0-060-52685-4",
                            ListPrice = 20.99m,
                            Pages = 320m,
                            StandardCost = 11.99m,
                            Writer = "Jim Collins"
                        },
                        new
                        {
                            BookId = 20,
                            BookCategoryId = 5,
                            BookName = "Becoming",
                            Edition = 1,
                            ISBNNumber = "978-0-525-57507-2",
                            ListPrice = 23.99m,
                            Pages = 448m,
                            StandardCost = 13.99m,
                            Writer = "Michelle Obama"
                        },
                        new
                        {
                            BookId = 21,
                            BookCategoryId = 9,
                            BookName = "The 7 Habits of Highly Effective People",
                            Edition = 1,
                            ISBNNumber = "978-0-7432-6951-0",
                            ListPrice = 21.99m,
                            Pages = 372m,
                            StandardCost = 12.99m,
                            Writer = "Stephen R. Covey"
                        },
                        new
                        {
                            BookId = 22,
                            BookCategoryId = 24,
                            BookName = "The Art of Happiness",
                            Edition = 1,
                            ISBNNumber = "978-1-57322-111-5",
                            ListPrice = 17.99m,
                            Pages = 320m,
                            StandardCost = 10.99m,
                            Writer = "Dalai Lama"
                        },
                        new
                        {
                            BookId = 23,
                            BookCategoryId = 22,
                            BookName = "Freakonomics",
                            Edition = 1,
                            ISBNNumber = "978-0-06-073132-6",
                            ListPrice = 16.99m,
                            Pages = 336m,
                            StandardCost = 9.99m,
                            Writer = "Steven D. Levitt, Stephen J. Dubner"
                        },
                        new
                        {
                            BookId = 24,
                            BookCategoryId = 30,
                            BookName = "The Catcher in the Rye",
                            Edition = 1,
                            ISBNNumber = "978-0-316-76948-0",
                            ListPrice = 14.99m,
                            Pages = 277m,
                            StandardCost = 8.99m,
                            Writer = "J.D. Salinger"
                        });
                });

            modelBuilder.Entity("BooksAPI.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookCategoryId");

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            BookCategoryId = 2,
                            CategoryName = "Non-Fiction"
                        },
                        new
                        {
                            BookCategoryId = 3,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            BookCategoryId = 4,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            BookCategoryId = 5,
                            CategoryName = "Biography"
                        },
                        new
                        {
                            BookCategoryId = 6,
                            CategoryName = "History"
                        },
                        new
                        {
                            BookCategoryId = 7,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            BookCategoryId = 8,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            BookCategoryId = 9,
                            CategoryName = "Self-Help"
                        },
                        new
                        {
                            BookCategoryId = 10,
                            CategoryName = "Cookbooks"
                        },
                        new
                        {
                            BookCategoryId = 11,
                            CategoryName = "Poetry"
                        },
                        new
                        {
                            BookCategoryId = 12,
                            CategoryName = "Travel"
                        },
                        new
                        {
                            BookCategoryId = 13,
                            CategoryName = "Business"
                        },
                        new
                        {
                            BookCategoryId = 14,
                            CategoryName = "Art & Photography"
                        },
                        new
                        {
                            BookCategoryId = 15,
                            CategoryName = "Technology"
                        },
                        new
                        {
                            BookCategoryId = 16,
                            CategoryName = "Philosophy"
                        },
                        new
                        {
                            BookCategoryId = 17,
                            CategoryName = "True Crime"
                        },
                        new
                        {
                            BookCategoryId = 18,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            BookCategoryId = 19,
                            CategoryName = "Graphic Novels"
                        },
                        new
                        {
                            BookCategoryId = 20,
                            CategoryName = "Health & Wellness"
                        },
                        new
                        {
                            BookCategoryId = 21,
                            CategoryName = "Psychology"
                        },
                        new
                        {
                            BookCategoryId = 22,
                            CategoryName = "Political Science"
                        },
                        new
                        {
                            BookCategoryId = 23,
                            CategoryName = "Music"
                        },
                        new
                        {
                            BookCategoryId = 24,
                            CategoryName = "Religion & Spirituality"
                        },
                        new
                        {
                            BookCategoryId = 25,
                            CategoryName = "Science & Nature"
                        },
                        new
                        {
                            BookCategoryId = 26,
                            CategoryName = "Parenting"
                        },
                        new
                        {
                            BookCategoryId = 27,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            BookCategoryId = 28,
                            CategoryName = "Anthropology"
                        },
                        new
                        {
                            BookCategoryId = 29,
                            CategoryName = "Education"
                        },
                        new
                        {
                            BookCategoryId = 30,
                            CategoryName = "Classics"
                        });
                });

            modelBuilder.Entity("BooksAPI.Models.Book", b =>
                {
                    b.HasOne("BooksAPI.Models.BookCategory", "ProductCategory")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("BooksAPI.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
